const SECTION_BY_PREFIX = [
  ["/items/", "itemNames"],
  ["/abilities/", "abilityNames"],
  ["/monsters/", "monsterNames"],
  ["/equipment_types/", "equipmentTypeNames"],
  ["/combat_styles/", "combatStyleNames"],
  ["/damage_types/", "damageTypeNames"],
  ["/skills/", "skillNames"],
  ["/buff_types/", "buffTypeNames"],
];

let translations = {};

const LOCAL_OVERRIDES = {
  "/buff_types/hp_regen":"生命恢复",
  "/buff_types/mp_regen":"法力恢复",
  "/house_rooms/archery_range": "射箭场",
  "/house_rooms/armory": "军械库",
  "/house_rooms/brewery": "酿造室",
  "/house_rooms/dairy_barn": "奶牛棚",
  "/house_rooms/dining_room": "餐厅",
  "/house_rooms/dojo": "道场",
  "/house_rooms/forge": "锻造房",
  "/house_rooms/garden": "花园",
  "/house_rooms/gym": "健身房",
  "/house_rooms/kitchen": "厨房",
  "/house_rooms/laboratory": "实验室",
  "/house_rooms/library": "图书馆",
  "/house_rooms/log_shed": "木料棚",
  "/house_rooms/mystical_study": "神秘书房",
  "/house_rooms/observatory": "观星台",
  "/house_rooms/sewing_parlor": "缝纫室",
  "/house_rooms/workshop": "工坊",
  "/combat_trigger_dependencies/all_allies": "全体友方",
  "/combat_trigger_dependencies/all_enemies": "全体敌方",
  "/combat_trigger_dependencies/self": "自身",
  "/combat_trigger_dependencies/targeted_enemy": "当前目标",
  "/combat_trigger_comparators/greater_than_equal": "大于或等于",
  "/combat_trigger_comparators/is_active": "已生效",
  "/combat_trigger_comparators/is_inactive": "未生效",
  "/combat_trigger_comparators/less_than_equal": "小于或等于",
  "/combat_trigger_conditions/current_hp": "当前生命",
  "/combat_trigger_conditions/current_mp": "当前法力",
  "/combat_trigger_conditions/missing_hp": "已损失生命",
  "/combat_trigger_conditions/missing_mp": "已损失法力",
  "/combat_trigger_conditions/lowest_hp_percentage": "最低生命百分比",
  "/combat_trigger_conditions/number_of_active_units": "存活单位数量",
  "/combat_trigger_conditions/number_of_dead_units": "死亡单位数量",
  "/combat_trigger_conditions/blind_status": "致盲状态",
  "/combat_trigger_conditions/silence_status": "沉默状态",
  "/combat_trigger_conditions/stun_status": "眩晕状态",
  "/combat_trigger_conditions/curse": "诅咒状态",
  "/combat_trigger_conditions/enrage": "激怒状态",
  "/combat_trigger_conditions/fury": "怒火状态",
  "/combat_trigger_conditions/weaken": "虚弱状态",
  "/buff_types/combat_experience": "战斗经验",
  "/buff_types/labyrinth_double_progress": "迷宫双倍进度",
  "/buff_types/max_hitpoints": "最大生命",
  "/buff_types/max_manapoints": "最大法力",
  "/buff_types/skilling_experience": "生产技能经验",
  "/buff_types/success_rate": "成功率",
  "/items/basic_coffee_crate": "基础咖啡补给箱",
  "/items/basic_food_crate": "基础食物补给箱",
  "/items/basic_tea_crate": "基础茶补给箱",
  "/items/advanced_coffee_crate": "高级咖啡补给箱",
  "/items/advanced_food_crate": "高级食物补给箱",
  "/items/advanced_tea_crate": "高级茶补给箱",
  "/items/expert_coffee_crate": "专家咖啡补给箱",
  "/items/expert_food_crate": "专家食物补给箱",
  "/items/expert_tea_crate": "专家茶补给箱",
  "/combat_trigger_conditions/attack_coffee": "攻击咖啡状态",
  "/combat_trigger_conditions/berserk": "狂暴状态",
  "/combat_trigger_conditions/channeling_coffee": "吟唱咖啡状态",
  "/combat_trigger_conditions/crippling_slash": "致残斩状态",
  "/combat_trigger_conditions/critical_aura": "暴击光环状态",
  "/combat_trigger_conditions/critical_coffee": "暴击咖啡状态",
  "/combat_trigger_conditions/defense_coffee": "防御咖啡状态",
  "/combat_trigger_conditions/elemental_affinity": "元素增幅状态",
  "/combat_trigger_conditions/elusiveness": "闪避状态",
  "/combat_trigger_conditions/fierce_aura": "物理光环状态",
  "/combat_trigger_conditions/fracturing_impact": "碎裂冲击状态",
  "/combat_trigger_conditions/frenzy": "狂速状态",
  "/combat_trigger_conditions/frost_surge": "冰霜爆裂状态",
  "/combat_trigger_conditions/guardian_aura": "守护光环状态",
  "/combat_trigger_conditions/ice_spear": "冰枪术状态",
  "/combat_trigger_conditions/insanity": "疯狂状态",
  "/combat_trigger_conditions/intelligence_coffee": "智力咖啡状态",
  "/combat_trigger_conditions/invincible": "无敌状态",
  "/combat_trigger_conditions/lucky_coffee": "幸运咖啡状态",
  "/combat_trigger_conditions/magic_coffee": "魔法咖啡状态",
  "/combat_trigger_conditions/maim": "血刃斩状态",
  "/combat_trigger_conditions/mana_spring": "法力喷泉状态",
  "/combat_trigger_conditions/melee_coffee": "近战咖啡状态",
  "/combat_trigger_conditions/mystic_aura": "元素光环状态",
  "/combat_trigger_conditions/pestilent_shot": "疫病射击状态",
  "/combat_trigger_conditions/precision": "精确状态",
  "/combat_trigger_conditions/provoke": "挑衅状态",
  "/combat_trigger_conditions/puncture": "破甲之刺状态",
  "/combat_trigger_conditions/ranged_coffee": "远程咖啡状态",
  "/combat_trigger_conditions/retribution": "惩戒状态",
  "/combat_trigger_conditions/smoke_burst": "烟爆灭影状态",
  "/combat_trigger_conditions/speed_aura": "速度光环状态",
  "/combat_trigger_conditions/spike_shell": "尖刺防护状态",
  "/combat_trigger_conditions/stamina_coffee": "耐力咖啡状态",
  "/combat_trigger_conditions/swiftness_coffee": "迅捷咖啡状态",
  "/combat_trigger_conditions/taunt": "嘲讽状态",
  "/combat_trigger_conditions/toughness": "坚韧状态",
  "/combat_trigger_conditions/toxic_pollen": "剧毒粉尘状态",
  "/combat_trigger_conditions/vampirism": "吸血状态",
  "/combat_trigger_conditions/wisdom_coffee": "经验咖啡状态"
,
  "/items/pathbreaker_boots": "开路者靴",
  "/items/pathbreaker_boots_refined": "开路者靴（精）",
  "/items/pathfinder_boots": "探路者靴",
  "/items/pathfinder_boots_refined": "探路者靴（精）",
  "/items/pathseeker_boots": "寻路者靴",
  "/items/pathseeker_boots_refined": "寻路者靴（精）",
  "/items/gatherer_cape": "采集者披风",
  "/items/gatherer_cape_refined": "采集者披风（精）",
  "/items/artificer_cape": "工匠披风",
  "/items/artificer_cape_refined": "工匠披风（精）",
  "/items/culinary_cape": "烹饪披风",
  "/items/culinary_cape_refined": "烹饪披风（精）",
  "/items/chance_cape": "机缘披风",
  "/items/chance_cape_refined": "机缘披风（精）",
  "/monsters/shadow_archer": "暗影弓手",
  "/monsters/pyre_hunter": "火焰猎手",
  "/monsters/frost_sniper": "霜冻狙击手",
  "/monsters/siren": "海妖",
  "/monsters/salamander": "火蜥蜴",
  "/monsters/dryad": "树精",
  "/monsters/giant_scorpion": "巨蝎",
  "/monsters/giant_mantis": "巨螳螂",
  "/monsters/cyclops": "独眼巨人",
  "/monsters/mimic": "宝箱怪",
};

export function installChineseTranslations(dictionary) {
  translations = dictionary && typeof dictionary === "object" ? dictionary : {};
}

export async function loadChineseTranslations(url = new URL("../data/zh.json", import.meta.url)) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`中文词条加载失败（${response.status}）`);
  installChineseTranslations(await response.json());
}

export function chineseName(hrid, fallback = "") {
  const id = String(hrid || "");
  if (LOCAL_OVERRIDES[id]) return LOCAL_OVERRIDES[id];
  const section = SECTION_BY_PREFIX.find(([prefix]) => id.startsWith(prefix))?.[1];
  const localized = section ? translations?.[section]?.[id] : "";
  return String(localized || fallback || id);
}
